#!/bin/bash
#
#	Build mbc into a Docker container, so we can test it locally
#
dir=$(cd `dirname $0`; pwd)
IMAGE_TAG=tooltwist/juiceconfig

cd ${dir}/..
pwd

ls -l server/pack*
ls -l website/pack*

echo "$" docker build -t ${IMAGE_TAG} .
         docker build -t ${IMAGE_TAG} .
