#!/bin/bash
#
#	Run the mbc Docker container, using the home volume found in this directory.
#
dir=$(cd `dirname $0`; pwd)
#echo dir=${dir}

#docker run -ti -p :4000 --rm -e SERVER_HOME=/Config/home juice-local-test /bin/sh
docker run -ti -p :4000 --rm -e JUICE_CONFIG=file:::/Config/server/config/serverConfig.js juice-local-test /bin/sh
